feat(STFE-9): implementation of teacher registration form
mohammed-sharraf-sazim/SuperTeacher-FE pull request #12
Opened 2024-08-27 15:19 UTC by mohammed-sharraf-sazim

## Description of Change

- Addition of Teacher Registration form

## Associated Ticket Link(s)
- https://trello.com/c/2EMl9xBY/9-subtask-21-design-the-teacher-registration-form

## Screenshots / Screen Recordings
- Screen Recording:

https://github.com/user-attachments/assets/43814dac-d729-4d8e-a172-535270adf468

- Screenshot(Large Screen):
![Screenshot 2024-08-27 at 9 10 38 PM](https://github.com/user-attachments/assets/1b7fd3ca-ee20-41ea-975f-5bd9e495d00c)
- Screenshot(Medium Screen):
![Screenshot 2024-08-27 at 9 11 34 PM](https://github.com/user-attachments/assets/147c5251-70b1-47a5-a367-1d73ffab6e4c)
- Screenshot(Small Screen):
![Screenshot 2024-08-27 at 9 10 38 PM](https://github.com/user-attachments/assets/00145af7-bf61-410a-b7e2-cffcf49d88e3)

2024-08-27 15:20 UTC, mohammed-sharraf-sazim commented
Sorry the screenshot for small screen will be this:
![Screenshot 2024-08-27 at 9 12 15 PM](https://github.com/user-attachments/assets/6db68e2f-8a6b-429f-8397-daa92b1c0263)

2024-08-28 05:52 UTC, nur-zaman-sazim requested changes

2024-08-28 05:52 UTC, nur-zaman-sazim commented on modules/RegisterUser/components/TeacherRegistration/TeacherForm.tsx
> +  ];
Please move this to constants file

2024-08-28 05:55 UTC, mahir-mohsin-sazim requested changes

2024-08-28 05:55 UTC, mahir-mohsin-sazim commented on modules/RegisterUser/components/TeacherRegistration/TeacherForm.tsx
> +  const options = [
Have this in a constants.ts file

2024-08-28 05:55 UTC, mahir-mohsin-sazim commented on modules/RegisterUser/containers/TeacherRegistrationContainer.tsx
> +import TeacherForm from "../components/TeacherRegistration/TeacherForm";
Use named exports for your own components

2024-08-28 05:55 UTC, mahir-mohsin-sazim commented on styles/globals.css
> +  /* body {
Remove this block if you do not require it

2024-08-31 07:28 UTC, mohammed-sharraf-sazim commented on modules/RegisterUser/components/TeacherRegistration/TeacherForm.tsx
> +  ];
Moved to the constants

2024-08-31 07:28 UTC, mohammed-sharraf-sazim commented on modules/RegisterUser/components/TeacherRegistration/TeacherForm.tsx
> +  const options = [
Moved

2024-08-31 07:28 UTC, mohammed-sharraf-sazim commented on modules/RegisterUser/containers/TeacherRegistrationContainer.tsx
> +import TeacherForm from "../components/TeacherRegistration/TeacherForm";
Used named exports

2024-08-31 07:28 UTC, mohammed-sharraf-sazim commented on styles/globals.css
> +  /* body {
Removed

2024-08-31 08:05 UTC, nur-zaman-sazim approved these changes

2024-08-31 08:05 UTC, nur-zaman-sazim approved these changes

2024-08-31 09:32 UTC, mahir-mohsin-sazim approved these changes

2024-08-31 09:45 UTC, merged