STFE-5: Implement student registration form
mohammed-sharraf-sazim/SuperTeacher-FE pull request #13
Opened 2024-08-29 15:15 UTC by mohammed-sharraf-sazim

## Description of Change
- Add student registration form
- Add BE integration with student registration form

## Associated Ticket Link(s)
- https://trello.com/c/FbLzdfZp/5-subtask-11-design-the-student-registration-form
- https://trello.com/c/oqpmTGI7/7-subtask-13-implement-conditional-fields-for-education-level

## Screenshots / Screen Recordings

https://github.com/user-attachments/assets/7b59a591-4cdb-4a2f-93b6-33e84761a720

2024-08-30 15:33 UTC, nur-zaman-sazim commented on modules/RegisterUser/components/StudentRegistration/StudentRegistration.hooks.ts
hooks should be in hooks folder `modules/RegisterUser/components/StudentRegistration/hooks/useYOUR_HOOK_NAME.ts`
move the mapping to a helper file.

2024-08-30 15:34 UTC, nur-zaman-sazim requested changes
Please Make Requested Changes.

2024-08-31 07:43 UTC, mohammed-sharraf-sazim commented on modules/RegisterUser/components/StudentRegistration/StudentRegistration.hooks.ts
I have discussed with ishmam bhaia before implementing that hooks and as per his suggestion it does not need to be in a folder and also in the nest js template it says that it can be in the component folder
<img width="384" alt="Screenshot 2024-08-31 at 1 30 33 PM" src="https://github.com/user-attachments/assets/442e1def-0e12-4f37-9f00-eff0be993602">

Mapper moved to a helper file

2024-08-31 08:34 UTC, nur-zaman-sazim approved these changes

2024-08-31 10:30 UTC, merged