chore(STFE-47): fix response type of user registration
mohammed-sharraf-sazim/SuperTeacher-FE pull request #16
Opened 2024-09-06 10:30 UTC by mohammed-sharraf-sazim

## Description of change
- Changed the output response type for both student and teacher to store the access token in local storage
- Made minor changes in zod validation and teacher form

##Associated Trello Link(s):
- https://trello.com/c/YpnoVvBH/47-create-a-response-type-for-student-and-teacher-auth

2024-09-06 19:04 UTC, mahir-mohsin-sazim approved these changes

2024-09-07 06:43 UTC, nur-zaman-sazim requested changes

2024-09-07 06:43 UTC, nur-zaman-sazim commented on modules/RegisterUser/components/TeacherRegistration/TeacherForm.hooks.ts
- Please remove the console logs from the file.
- [nit] better to put the mapper in a separate file.
- `res` seems too generic for a variable name 
- instead of using try catch can't we use something like `const [registerTeacher, { isLoading, isError, error, isSuccess }] = useRegisterTeacherMutation();` to pull the error ?

2024-09-09 04:52 UTC, mahir-mohsin-sazim requested changes

2024-09-09 04:52 UTC, mahir-mohsin-sazim commented on modules/RegisterUser/components/StudentRegistration/StudentRegistration.helpers.ts
> +      .min(6, "Password must be at least 8 characters")
check the validation logic please

2024-09-23 13:51 UTC, mohammed-sharraf-sazim commented on modules/RegisterUser/components/StudentRegistration/StudentRegistration.helpers.ts
> +      .min(6, "Password must be at least 8 characters")
Corrected the validation error

2024-09-25 06:32 UTC, nur-zaman-sazim approved these changes

2024-09-25 10:16 UTC, merged