STFE-23: teacher dashboard and classroom form
mohammed-sharraf-sazim/SuperTeacher-FE pull request #17
Opened 2024-09-11 07:46 UTC by mohammed-sharraf-sazim

## Description of change:
- Add User Dashboard for both teachers and students
- Add Classroom Form
- Integrate BE apis to the FE for classroom creation
## Associated Trello Link(s):
- https://trello.com/c/y99QPQ6J/23-subtask-162-fe-create-and-manage-classrooms
## Screenshots/Screen recordings:
- 
![Screenshot 2024-09-11 at 1 40 40 PM](https://github.com/user-attachments/assets/ccda197b-105d-4054-bb2b-9a1638312e74)
- 
![Screenshot 2024-09-11 at 1 41 08 PM](https://github.com/user-attachments/assets/03b8a385-89a9-4860-9d49-dfc2a7915da6)

2024-09-12 08:18 UTC, mahir-mohsin-sazim requested changes

2024-09-12 08:18 UTC, mahir-mohsin-sazim commented on modules/UserDashboard/containers/ClassroomContainer/ClassroomContainer.tsx
> +import Navbar from "../../components/Navbar/Navbar";
use Default exports please

2024-09-12 08:18 UTC, mahir-mohsin-sazim commented on modules/UserDashboard/containers/DashboardContainer.tsx
> +import ClassroomContainer from "./ClassroomContainer/ClassroomContainer";
use Default exports

2024-09-12 08:18 UTC, mahir-mohsin-sazim commented on modules/UserDashboard/components/Navbar/Navbar.tsx
> +        <Button className="bg-[#0e162c] px-3 py-1 sm:px-4 sm:py-2 rounded text-xs sm:text-sm  hover:bg-gray-900">
it will be better if you can shorted classNames for these two button as they both are using the same classes. Look into `@base` `@layer` and `@apply` directives in tailwindcss

2024-09-12 08:18 UTC, mahir-mohsin-sazim commented on modules/AddClassroom/components/ClassroomForm.tsx
> +    mode: "onChange",
can you explain in brief the purpose of `mode`

2024-09-12 08:18 UTC, mahir-mohsin-sazim commented on modules/AddClassroom/components/ClassroomForm.tsx
> +                      <SelectItem value="Mathematics">Mathematics</SelectItem>
please refactor this. Use an array and iterate through that

2024-09-12 08:18 UTC, mahir-mohsin-sazim commented on modules/AddClassroom/components/ClassroomForm.hooks.ts
> +                console.log(response);
remove it

2024-09-12 08:18 UTC, mahir-mohsin-sazim commented on modules/AddClassroom/components/ClassroomForm.hooks.ts
> +                toast.success("New Classroom Created! ");
[NITPICK] remove extra spaces please

2024-09-12 08:18 UTC, mahir-mohsin-sazim commented on modules/AddClassroom/components/ClassroomForm.hooks.ts
> +              console.log(error);
You must do error handling properly. Please fix that

2024-09-21 13:07 UTC, nur-zaman-sazim requested changes

2024-09-21 13:07 UTC, nur-zaman-sazim commented on modules/AddClassroom/components/ClassroomForm.helper.ts
> +  classTimeDate.setHours(hours, minutes, 0, 0);
better to use date-fns (startofday)

2024-09-21 13:07 UTC, nur-zaman-sazim commented on modules/AddClassroom/components/ClassroomForm.hooks.ts
> +        const classTimeDate = convertTimeToDate(classroomData.classTime);
use can directly use date-fns here

2024-09-23 14:44 UTC, mohammed-sharraf-sazim commented on modules/UserDashboard/components/Navbar/Navbar.tsx
> +        <Button className="bg-[#0e162c] px-3 py-1 sm:px-4 sm:py-2 rounded text-xs sm:text-sm  hover:bg-gray-900">
1. There is a difference in the hovering and border for the buttons do I need to change?

2024-09-23 14:49 UTC, mohammed-sharraf-sazim commented on modules/AddClassroom/components/ClassroomForm.tsx
> +    mode: "onChange",
the mode "onChange" will check for validation errors as the user types or selects options.

2024-09-23 14:57 UTC, mohammed-sharraf-sazim commented on modules/AddClassroom/components/ClassroomForm.helper.ts
> +  classTimeDate.setHours(hours, minutes, 0, 0);
Used it

2024-09-23 15:05 UTC, mohammed-sharraf-sazim commented on modules/AddClassroom/components/ClassroomForm.hooks.ts
> +                console.log(response);
removed

2024-09-23 15:05 UTC, mohammed-sharraf-sazim commented on modules/AddClassroom/components/ClassroomForm.tsx
> +                      <SelectItem value="Mathematics">Mathematics</SelectItem>
Array has been used

2024-09-24 10:34 UTC, nur-zaman-sazim approved these changes

2024-09-25 10:16 UTC, merged