STFE-52: add classroom cards
mohammed-sharraf-sazim/SuperTeacher-FE pull request #18
Opened 2024-09-12 06:43 UTC by mohammed-sharraf-sazim

## Description of change:
- Add teacher and student classrooms dashboard

## Associated Trello Link(s):
- https://trello.com/c/dE7O4CHj/52-classroom-card-components-fe

## Related Pull Request(s):
- https://github.com/mohammed-sharraf-sazim/SuperTeacher-FE/pull/17

## Screenshots
- 
![Screenshot 2024-09-12 at 12 40 58 PM](https://github.com/user-attachments/assets/22b15d6e-5bb6-4274-b2da-6727b0f3b548)
- 
![Screenshot 2024-09-12 at 12 41 19 PM](https://github.com/user-attachments/assets/93abbc1b-29b1-4dc8-9fae-509f8ac6f491)

- 
![Screenshot 2024-09-12 at 12 42 02 PM](https://github.com/user-attachments/assets/ce920463-e995-4844-a3d7-ce33d6a9b213)

2024-09-12 08:21 UTC, mahir-mohsin-sazim requested changes
Please if for mobile screens, all your cards are center aligned or not. From the images you have attached, I do not think they are properly aligned

2024-09-12 08:21 UTC, mahir-mohsin-sazim commented on modules/UserDashboard/containers/ClassroomContainer/ClassroomContainer.tsx
> +import ClassroomCard from "@/modules/ClassroomCard/ClassroomCard";
use Default export

2024-09-12 08:21 UTC, mahir-mohsin-sazim commented on modules/UserDashboard/containers/ClassroomContainer/ClassroomContainer.tsx
>  import Navbar from "../../components/Navbar/Navbar";
use default export

2024-09-12 08:21 UTC, mahir-mohsin-sazim commented on modules/UserDashboard/containers/ClassroomContainer/ClassroomContainer.tsx
> +    console.log(data);
remove this

2024-09-12 11:41 UTC, mohammed-sharraf-sazim commented on modules/UserDashboard/containers/ClassroomContainer/ClassroomContainer.tsx
>  import Navbar from "../../components/Navbar/Navbar";
resolved

2024-09-12 11:42 UTC, mohammed-sharraf-sazim commented on modules/UserDashboard/containers/ClassroomContainer/ClassroomContainer.tsx
> +    console.log(data);
removed

2024-09-13 08:22 UTC, mahir-mohsin-sazim approved these changes

2024-09-21 13:11 UTC, nur-zaman-sazim approved these changes
Left some nitpicks

2024-09-21 13:11 UTC, nur-zaman-sazim commented on modules/ClassroomCard/ClassroomCard.tsx
> +import React from "react";
nit: we don't need this line

2024-09-21 13:11 UTC, nur-zaman-sazim commented on modules/UserDashboard/components/Navbar/Navbar.tsx
> +import React, { useState } from "react";
nit: same comment as before

2024-09-25 10:22 UTC, merged